<html>
<head>
    <title>Tales - Terms of Service</title>
</head>
<body>
<h1>Terms of Service</h1>

<p>These Terms of Service ("Agreement") govern your use of the website [Tales-GCA] ("Tales"). By accessing or using the Website, you agree to be bound by these terms and conditions. If you do not agree with any part of these terms and conditions, you must not use the Website.</p>

<h2>1. User Conduct</h2>

<p>By using the Website, you agree to:</p>
<ul>
    <li>Upload only family-friendly images, including those generated by AI, but only if explicitly selected during the upload process.</li>
    <li>Not steal or infringe upon the intellectual property rights of others, including art and images.</li>
    <li>Not engage in any illegal activities or use the Website for illegal purposes.</li>
    <li>Comply with all applicable laws and regulations.</li>
</ul>

<h2>2. Content Ownership</h2>

<p>You retain ownership of the images and descriptions you upload to the Website. However, by uploading content, you grant [Tales-GCA] a non-exclusive, royalty-free, worldwide license to use, reproduce, modify, adapt, publish, translate, distribute, and display the content for the purpose of operating and promoting the Website.</p>

<h2>3. Disclaimer of Liability</h2>

<p>[Tales-GCA] and its owners do not take any responsibility for the content uploaded by users. We do not endorse or guarantee the accuracy, completeness, or usefulness of any content on the Website. Users are solely responsible for their use of the Website and any consequences that may arise from it.</p>

<h2>4. Intellectual Property</h2>

<p>All intellectual property rights in the Website and its content, including but not limited to text, graphics, logos, images, and software, are owned by [Tales-GCA] or its licensors. You may not use, reproduce, modify, adapt, distribute, or display any part of the Website without prior written permission from [Tales-GCA].</p>

<h2>5. Governing Law and Jurisdiction</h2>

<p>This Agreement shall be governed by and construed in accordance with the laws of [European Union (EU)]. Any disputes arising out of or in connection with this Agreement shall be subject to the exclusive jurisdiction of the courts of [European Union (EU)].</p>

<h2>6. Modifications to the Agreement</h2>

<p>[Tales-GCA] reserves the right to modify or update these terms and conditions at any time without prior notice. It is your responsibility to review this Agreement periodically for changes. Your continued use of the Website after any modifications to this Agreement constitutes your acceptance of the modified terms and conditions.</p>

<h2>7. Contact Information</h2>

<p>If you have any questions or concerns about these Terms of Service, please contact us at [<a href="mailto:anonymousgca@tales.anonymousgca.eu">anonymousgca@tales.anonymousgca.eu</a>].</p>

</body>
</html>